Repository fastapi-mvc/fastapi-mvc, pull requests merged in 2022-01, with the labels that each got.

#11 Add release and publish workflow
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  CHANGELOG.md
  TAG
  fastapi_mvc/template/{{cookiecutter.folder_name}}/.github/workflows/main.yml
  fastapi_mvc/version.py
  pyproject.toml
Labels: enhancement

#12 Add docs
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  assets/ci.png
  assets/readme.gif
  build/install.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/README.md
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/dev-env.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/install.sh
Labels: documentation

#20 Improve make target scripts both for package and template
  .github/workflows/integration.yml
  CHANGELOG.md
  README.md
  build/clean-image.sh
  build/image.sh
  build/install.sh
  build/integration-test.sh
  build/metrics.sh
  build/unit-test.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/clean-image.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/image.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/install.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/integration-test.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/metrics.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/unit-test.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/controllers/api/v1/ready.py
Labels: feature

#22 Implement all HTTP methods in aiohttp utility
  .github/workflows/main.yml
  CHANGELOG.md
  fastapi_mvc/template/{{cookiecutter.folder_name}}/.github/workflows/main.yml
  fastapi_mvc/template/{{cookiecutter.folder_name}}/tests/unit/app/utils/test_aiohttp_client.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/utils/aiohttp_client.py
Labels: feature

#23 Improve container reproducibility and security
  Dockerfile
  README.md
  build/install.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/Dockerfile
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/install.sh
Labels: feature

#27 Release 0.7.0
  CHANGELOG.md
  Dockerfile
  fastapi_mvc/template/{{cookiecutter.folder_name}}/Dockerfile
  fastapi_mvc/template/{{cookiecutter.folder_name}}/README.md
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/unit-test.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/tests/unit/cli/commands/test_serve.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/tests/unit/test_wsgi.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/cli/commands/serve.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/wsgi.py
Labels: feature, template
