Repository fastapi-mvc/fastapi-mvc, pull requests merged in 2022-06, with the labels that each got.

#100 Fix typos
  docs/generated-project.rst
  docs/quickstart.rst
  fastapi_mvc/borg.py
Labels: documentation

#101 Add initial generators documentation
  CHANGELOG.md
  docs/conf.py
  docs/generators.rst
  docs/index.rst
  fastapi_mvc/generators/base.py
  fastapi_mvc/generators/controller/controller.py
  fastapi_mvc/generators/generator/generator.py
  fastapi_mvc/generators/generator/template/{{cookiecutter.folder_name}}/lib/generators/{{cookiecutter.generator_name}}/{{cookiecutter.generator_name}}.py
  fastapi_mvc/generators/project/project.py
Labels: documentation

#103 Add generator template minor fix
  CHANGELOG.md
  fastapi_mvc/generators/generator/template/{{cookiecutter.folder_name}}/lib/generators/{{cookiecutter.generator_name}}/{{cookiecutter.generator_name}}.py
  tests/unit/data/lib/generators/foobar/foobar.py
  tests/unit/data/lib/generators/my_controller/my_controller.py
Labels: bug

#104 Add integration tests for generators
  CHANGELOG.md
  fastapi_mvc/generators/generator/template/hooks/post_gen_project.py
  tests/integration/test_controller_cookiecutter.py
  tests/integration/test_generator_cookiecutter.py
  tests/integration/test_project_cookiecutter.py
Labels: enhancement

#105 Add support for binding gunicorn server to a UNIX socket
  CHANGELOG.md
  docs/generated-project.rst
  fastapi_mvc/generators/project/template/{{cookiecutter.folder_name}}/README.md
  fastapi_mvc/generators/project/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/cli/serve.py
  fastapi_mvc/generators/project/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/config/gunicorn.py
Labels: enhancement, project template
