Repository fastapi-mvc/fastapi-mvc, pull requests merged in 2022-04, with the labels that each got.

#58 Add improvements
  .gitignore
  CHANGELOG.md
  README.md
  build/install.sh
  docs/install.md
  docs/usage/development.md
  fastapi_mvc/template/{{cookiecutter.folder_name}}/README.md
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/install.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/shell.nix
  shell.nix
  tests/unit/utils/test_shell.py
Labels: enhancement

#61 Fix install fail when Python version >= 3.10
  .github/workflows/main.yml
  CHANGELOG.md
  build/install.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/.github/workflows/main.yml
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/install.sh
Labels: bug

#65 Update poetry
  build/metrics.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: bug, automation

#83 Add sphinx docs
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  build/docs.sh
  docs/CHANGELOG.md
  docs/CONTRIBUTING.md
  docs/_static/ci.png
  docs/_static/docs_page.png
  docs/_static/k8s_arch.png
  docs/_static/logo.png
  docs/_static/readme.gif
  docs/about.rst
  docs/api.rst
  docs/conf.py
  docs/deployment.rst
  docs/deployment/docker.md
  docs/deployment/kubernetes.md
  docs/deployment/manually.md
  docs/generated-project.rst
  docs/generators.rst
  docs/index.md
  docs/index.rst
  docs/install.md
  docs/license.rst
  docs/quickstart.rst
  docs/usage/configuration.md
  docs/usage/create.md
  docs/usage/development.md
  fastapi_mvc/borg.py
  fastapi_mvc/cli/generate.py
  fastapi_mvc/cli/new.py
  fastapi_mvc/cli/run.py
  fastapi_mvc/commands/base.py
  fastapi_mvc/commands/generate.py
  fastapi_mvc/commands/invoker.py
  fastapi_mvc/commands/run_shell.py
  fastapi_mvc/generators/base.py
  fastapi_mvc/generators/controller/controller.py
  fastapi_mvc/generators/generator/generator.py
  fastapi_mvc/generators/loader.py
  fastapi_mvc/generators/project.py
  fastapi_mvc/parsers/ini.py
  fastapi_mvc/utils/shell.py
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#86 Run poetry with abspath, fix `fastapi-mvc run` implementation
  CHANGELOG.md
  README.md
  docs/index.rst
  docs/quickstart.rst
  fastapi_mvc/borg.py
  fastapi_mvc/cli/run.py
  tests/unit/cli/test_run.py
  tests/unit/test_borg.py
Labels: bug

#88 Migrate to new poetry script
  CHANGELOG.md
  build/install.sh
  fastapi_mvc/template/{{cookiecutter.folder_name}}/build/install.sh
Labels: enhancement

#91 Cleanup
  CHANGELOG.md
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/asgi.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/controllers/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/controllers/api/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/controllers/api/v1/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/controllers/api/v1/ready.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/exceptions/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/models/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/models/ready.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/models/response.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/utils/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/utils/aiohttp_client.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/app/utils/redis.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/cli/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/cli/cli.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/cli/commands/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/cli/commands/serve.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/config/__init__.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/config/application.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/config/redis.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/version.py
  fastapi_mvc/template/{{cookiecutter.folder_name}}/{{cookiecutter.package_name}}/wsgi.py
Labels: cleanup

#94 Extend and improve k8s integration workflow
  .github/workflows/integration.yml
  CHANGELOG.md
  fastapi_mvc/template/{{cookiecutter.folder_name}}/Vagrantfile
Labels: automation
